# Generated by Django 4.2 on 2023-05-03 20:38

from django.db import migrations, models
import django.utils.timezone
import vectordb.models


class Migration(migrations.Migration):
    dependencies = [
        ("vectordb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vector",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vector",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vector",
            name="embedding",
            field=models.BinaryField(validators=[vectordb.models.validate_embedding]),
        ),
    ]
